spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://jatinbalar1.b2clogin.com/29f84888-85d5-4d9a-958a-b730f55dd550/v2.0/"
          jwk-set-uri: "https://jatinbalar1.b2clogin.com/jatinbalar1.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi"
  h2: 
    console:
      enabled: true  
  datasource: 
    url: jdbc:h2:mem:testdb 
  jpa: 
    defer-datasource-initialization: true
  main: 
    banner-mode: off    
logging:
  level: 
    org: 
      springframework: debug
  pattern.console: "%d{MM-dd HH:mm:ss} - %logger{36} - %msg%n"
