spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://jatinbalar.b2clogin.com/55515a48-54c0-43da-8441-b64331c10d4d/v2.0/"
          jwk-set-uri: "https://jatinbalar.b2clogin.com/jatinbalar.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_susi"